# Generated by Django 5.1.2 on 2024-12-31 06:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Medicines",
            fields=[
                ("medicine_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("composition", models.TextField()),
                ("company", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Tests",
            fields=[
                ("test_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("test_type", models.CharField(max_length=50)),
                ("prep_condition", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="PatientDetails",
            fields=[
                (
                    "patient_ID",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("age", models.IntegerField()),
                ("weight", models.FloatField()),
                ("height", models.FloatField()),
                ("temperature", models.FloatField()),
                ("blood_pressure", models.CharField(max_length=15)),
                ("BMI", models.FloatField()),
                ("O2_level", models.FloatField()),
                ("symptoms", models.TextField()),
                ("date_visited", models.DateField()),
                ("date_treated", models.DateField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_details",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PatientQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("queue_position", models.IntegerField()),
                ("date_enqueued", models.DateTimeField()),
                ("time_expired", models.DateTimeField(blank=True, null=True)),
                (
                    "patient_details",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queue",
                        to="PatientManagement.patientdetails",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "prescription_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("date_generated", models.DateField()),
                ("date_valid_upto", models.DateField()),
                (
                    "patient_details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="PatientManagement.patientdetails",
                    ),
                ),
            ],
        ),
    ]
