# Generated by Django 5.1.2 on 2025-01-12 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("PatientManagement", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Medicines",
        ),
        migrations.RemoveField(
            model_name="patientdetails",
            name="user",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="patient_details",
        ),
        migrations.RemoveField(
            model_name="patientqueue",
            name="patient_details",
        ),
        migrations.DeleteModel(
            name="Tests",
        ),
        migrations.DeleteModel(
            name="Prescription",
        ),
        migrations.DeleteModel(
            name="PatientDetails",
        ),
        migrations.DeleteModel(
            name="PatientQueue",
        ),
    ]
