# Generated by Django 5.1.2 on 2025-01-12 06:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "PatientManagement",
            "0002_delete_medicines_remove_patientdetails_user_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Medicines",
            fields=[
                (
                    "medicine_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("composition", models.TextField()),
                ("company", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "medicines",
            },
        ),
        migrations.CreateModel(
            name="Tests",
            fields=[
                (
                    "test_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("type_of_test", models.CharField(max_length=50)),
                ("prep_condition", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "tests",
            },
        ),
        migrations.CreateModel(
            name="PatientDetails",
            fields=[
                (
                    "patient_ID",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "blood_pressure",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "BMI",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "O2level",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "blood_sugar",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("symptoms", models.TextField(blank=True, null=True)),
                ("date_visited", models.DateField(blank=True, null=True)),
                ("date_treated", models.DateField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "patient_details",
            },
        ),
        migrations.CreateModel(
            name="PatientQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("queue_position", models.PositiveIntegerField()),
                ("date_enqueued", models.DateField(default=django.utils.timezone.now)),
                ("time_enqueued", models.TimeField(default=django.utils.timezone.now)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queue_entries",
                        to="PatientManagement.patientdetails",
                    ),
                ),
            ],
            options={
                "db_table": "patient_queue",
            },
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "prescription_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_generated", models.DateField(default=django.utils.timezone.now)),
                ("date_valid_upto", models.DateField(blank=True, null=True)),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="PatientManagement.patientdetails",
                    ),
                ),
            ],
            options={
                "db_table": "prescriptions",
            },
        ),
    ]
