# Generated by Django 5.1.2 on 2025-01-12 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(blank=True, max_length=30)),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("doctor", "doctor"),
                            ("staff", "staff"),
                            ("patient", "patient"),
                        ],
                        default="patient",
                        max_length=10,
                    ),
                ),
                ("mobile", models.CharField(blank=True, max_length=10, null=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("date_registered", models.DateTimeField(auto_now_add=True)),
                ("otp", models.IntegerField(blank=True, null=True)),
                ("otp_expiry", models.DateTimeField(blank=True, null=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "custom_user",
                "verbose_name_plural": "custom_users",
                "db_table": "custom_user",
            },
        ),
    ]
